{{- $root := . }}

{{- $linuxDefaultImg := "bash:5.3.20" }}
{{- $linuxDefaultMemory := "200Mi" }}
{{- $linuxDefaultCpu := "200m" }}

{{- $networkTypeMap := include "netclab.networkTypeMap" $root | fromYaml }}

{{- range $i, $node := .Values.topology.nodes }}
{{- $nodeName := .name }}
{{- if eq .type "linux" }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .name }}
  labels:
    {{- include "netclab.labels" $root | nindent 4 }}
    {{ $root.Chart.Name }}/pod-name: {{ .name }}
  annotations:
    k8s.v1.cni.cncf.io/networks: {{ include "netclab.nodeNetworks" (dict "node" $node "networkTypeMap" $networkTypeMap "root" $root) }}
spec:
  terminationGracePeriodSeconds: 0
  affinity:
    {{- include "netclab.podAffinity" $root | nindent 4 }}
  containers:
  - image: {{ default $linuxDefaultImg .image }}
    name: {{ .name }}
    args:
    - sh
    - -c
    - sleep inf
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    resources:
      limits:
        cpu: {{ default $linuxDefaultCpu .cpu }}
        memory: {{ default $linuxDefaultMemory .memory }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "netclab.labels" $root | nindent 4 }}
    {{ $root.Chart.Name }}/pod-name: {{ .name }}
  name: {{ .name }}
spec:
  selector:
    {{- include "netclab.labels" $root | nindent 4 }}
    {{ $root.Chart.Name }}/pod-name: {{ .name }}
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22

{{- end }}
{{- end }}
