{{- if .Capabilities.APIVersions.Has "k8s.cni.cncf.io/v1" }}
{{- $root := . }}

{{- $networkTypeMap := include "netclab.networkTypeMap" $root | fromYaml }}

{{- range .Values.topology.networks }}

{{- if eq (index $networkTypeMap .name) "veth" }}
{{- $networkName := .name }}
{{- range $root.Values.topology.nodes }}
{{- $nodeName := .name }}
{{- range .interfaces }}
{{- if eq .network $networkName }}

{{- $hostDeviceName := include "netclab.vethName" (dict
      "release" $root.Release.Name
      "network" $networkName
      "node"    $nodeName
  ) }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ $hostDeviceName }}
  labels: {{- include "netclab.labels" $root | nindent 4 }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "{{ $hostDeviceName }}",
      "plugins": [
        {
          "type": "host-device",
          "device": "{{ $hostDeviceName }}",
          "ipam": {}
        }
      ]
    }'

{{- end}} # if eq .network $networkName
{{- end}}  # range .interfaces
{{- end}}  # range $root.Values.topology.nodes
{{- else}} # if eq (index $networkTypeMap .name) "veth"
{{- $hostBridgeName := printf "%s-%s" $root.Release.Name .name }}
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ $hostBridgeName }}
  labels: {{- include "netclab.labels" $root | nindent 4 }}
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "{{ $hostBridgeName }}",
      "plugins": [
        {
          "type": "bridge",
          "bridge": "{{ $hostBridgeName }}",
          "ipam": {}
        }
      ]
    }'
{{- end }} # if eq (index $networkTypeMap .name) "veth"

{{- end }} # range .Values.topology.networks
{{- else }} # if .Capabilities.APIVersions.Has "k8s.cni.cncf.io/v1"
{{ fail "❌ Multus CNI CRD (k8s.cni.cncf.io/v1) not found. Install Multus before proceeding." }}
{{- end }} # if .Capabilities.APIVersions.Has "k8s.cni.cncf.io/v1"
